### ISSUE TITLE
Following List?

### ISSUE THREAD

**Issue by dinosaw** [mwalbeck/twitchlite#1]
Hello!

This is a very simple, basic PHP application that I've been looking for. However I was wondering if it was possible to do/add one thing with it. Instead of just pulling the top streamers, or streamers of a particular game, I was wondering if it would be possible to pull and display a list of streamers that an account follows?

For example, my use case is that I want a PHP/web page to display only the streamers that I follow that are streaming live.

Thanks!

**Comment by mwalbeck** [comment]
Glad you like it.

I just looked at the twitch api docs and this shouldn't be a problem, so I'll see what I can do.

**Comment by mwalbeck** [comment]
I've push some code that implements it using an oauth token. I've some changes I want to make to it, like choosing which view you want as default and a few other improvements. Though, I won't have time to continue working on it until next week. You can check out the README for a bit more info.

**Comment by dinosaw** [comment]
This worked perfectly, and I love the new layout! Thanks so much!

**Comment by mwalbeck** [comment]
You can now choose to have followed streams as default view.
