### ISSUE TITLE
Limit Not Working

### ISSUE THREAD

**Issue by dinosaw** [mwalbeck/twitchlite#2]
Hello again! I noticed there's an issue with the limit field not being applied. No matter what you specify, it always pulls Twitch's API default which I believe is 25. Not sure if it matters, but my PHP version is `5.6.30`. Would you be able to look into this? Again, really love the whole "lite" aspect of this.

Also, this is kind a feature suggestion which I hate to bug you again with one (and I can create a new issue for you if you'd like to be able to reference something in your commits) but having pagination added would be great. Basically having a "Page 2 / Page 3" or "Next Page / Previous Page" kinda thing.

**Comment by mwalbeck** [comment]
Hey there,

The limit fields is working fine for me on PHP version 5.6.30, so I would need some more info about your setup to be of any help. As a start, if you can provide me with the server os, webserver and browser, both which you are using and the version number, that would be great.

Nothing wrong with a feature request when they are within the scope of the project as this one is, but please do make a new issue for it.

**Comment by dinosaw** [comment]
Thanks for the reply! I was running it locally on my Windows machine but went ahead and moved it over to my test server/domain and still having the same problem. I haven't modified anything - just a simple `git clone` and configured permissions/ownership, etc. Also monitoring the Apache logs I'm not seeing any errors.

Edit: Oh and I'm using Chrome 61.0.3163.100 (Official Build) (64-bit) (cohort: Stable)

Link:
```
?limit=100&offset=0&game=
```
Edit (by mwalbeck): Removed above links

Info:
```
[root@server-02 twitchlite]# cat /etc/*-release
CentOS release 6.9 (Final)
[root@server-02 twitchlite]# php -v
PHP 5.6.30 (cli) (built: Jan 20 2017 08:02:17)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
[root@server-02 twitchlite]# httpd -v
Server version: Apache/2.2.15 (Unix)
Server built:   Nov 15 2012 15:52:50
```

Loaded PHP Modules (php -m)
```
bcmath bz2 calendar Core ctype curl date dom ereg exif fileinfo filter ftp gd gettext gmp hash iconv imap intl json ldap libxml mbstring mcrypt mhash mysql mysqli mysqlnd openssl pcntl pcre PDO pdo_mysql pdo_sqlite Phar posix pspell readline recode Reflection session shmop SimpleXML soap sockets SPL sqlite3 standard sysvmsg sysvsem sysvshm tidy tokenizer wddx xml xmlreader xmlrpc xmlwriter xsl zip zlib
```

**Comment by mwalbeck** [comment]
Thanks for the info. The links helped a lot as the problem only occurs when setting the limit to 100. It was a silly little mistake when checking if the set limit was valid.

I've taken the precaution of removing your links from your comment, just in case.

**Comment by dinosaw** [comment]
Well shoot, that was just poor testing on my behalf. Apologies for that. I could've sworn I tested more than just 100, but seems like you're right! And I appreciate removing those links, as that's really just for my personal dev purposes. Thanks again!
