### ISSUE TITLE
Adding Pagination

### ISSUE THREAD

**Issue by dinosaw** [mwalbeck/twitchlite#3]
I *think* this should be possible, but essentially it would be great to have something such as a "next page, previous page" or "page 1, page 2" type of navigation. At least for the `/streams/` endpoint. 

An example query: `/kraken/streams?limit=25&offset=25&stream_type=live`

Produces pagination information in `_links`:

```
_links: {
self: "https://api.twitch.tv/kraken/streams?limit=25&offset=25&stream_type=live",
next: "https://api.twitch.tv/kraken/streams?limit=25&offset=50&stream_type=live",
prev: "https://api.twitch.tv/kraken/streams?limit=25&offset=0&stream_type=live",
featured: "https://api.twitch.tv/kraken/streams/featured",
summary: "https://api.twitch.tv/kraken/streams/summary",
followed: "https://api.twitch.tv/kraken/streams/followed"
}
```

**Comment by mwalbeck** [comment]
I have added some simple pagnation.

Also I have added support for a config file which should make git pulls a bit easier. There is a bit more info in the readme

**Comment by dinosaw** [comment]
Thanks for the changes. Working well here!
