### ISSUE TITLE
Search Game Not Working When "followed" Checked

### ISSUE THREAD

**Issue by dinosaw** [mwalbeck/twitchlite#5]
Hello again!

I'm not sure if you're still working on this project, but I still use it to this day. I only recently attempted searching for a game when I had the "Followed" checkmark enabled, and realized that it doesn't actually search for a game. It basically just lists out all the streamers that the corresponding oauth token is following.

Are you able to fix this so where I can have the Followed box checked, and still be able to search games and have them correctly populate?

Thanks again for this!

**Comment by mwalbeck** [comment]
Hi,

I've been away from my home server for quite a while and it needed an overhaul recently and I have been wanting to setup this project again, so I don't see any issue updating it.

Searching in followed streams isn't supported by the api but should be pretty easy to implement with a loop after the api call. I'll have a look at it when I redeploy it on my own server.

**Comment by dinosaw** [comment]
Awesome! I appreciate you taking a look into this!

**Comment by mwalbeck** [comment]
All done. I've also added an option to specify how many game names are pulled for auto-completion, the default is still 10, but can be between 1-100.

**Comment by dinosaw** [comment]
Thanks for adding this. It seems to check out. However there does appear to be a small bug. When searching for a game, it is case-sensitive. For example `planet zoo` does not bring up the streamers streaming the correct title of `Planet Zoo`. This could possibly cause some issues for streamers who don't let auto-fill on their Twitch dashboard fix the capitalization of the titles.

**Comment by mwalbeck** [comment]
Thanks for the heads up, I've made it so the titles are converted to lowercase before comparison.
